### ISSUE TITLE
status sync back to coffeebreak does not work

### ISSUE THREAD

**Issue by lioman** [frenya/vscode-coffeebreak-todoist#1]
## Steps to reproduce

- add task in vscode
- sync with todoist
- complete task in todoist
- sync in vscode again

## Expected:

Status in coffeebreak file changes to "[X]"

**Comment by frenya** [comment]
Hi. Thanks for reaching out. This has not been implemented yet. I planned to implement it in one of the future versions. I will increase the priority of this ;)

In the meantime this must be done manually. The backlink in the task in Todoist should simplify it a bit I hope.

**Comment by frenya** [comment]
The completion status is now synced back from Todoist.
