### ISSUE TITLE
Syncing always creates new tasks in Todoist

### ISSUE THREAD

**Issue by kenlefeb** [frenya/vscode-coffeebreak-todoist#9]
I just installed Coffee Break, this morning, so it's entirely possible I'm doing something wrong, but every time I sync from VS Code to Todoist, new tasks are being created, even if no changes were made to the tasks in VS Code. Is this a known issue, or perhaps an ignorant user?

**Comment by frenya** [comment]
Hi Kenneth, this is definitely not the expected behavior. Let me ask you first - when you run the sync, do you see Todoist links being added at the end of each synchronized task? (something like `[](https://todoist.com/showTask?id=123456789)`)

**Comment by kenlefeb** [comment]
You mean in my markdown? No, I don't. Maybe I'm formatting my tasks incorrectly?

![image](https://user-images.githubusercontent.com/1662682/129066552-cdb8f097-79e3-439a-a437-056ec3b0b5fa.png)

**Comment by frenya** [comment]
I have just published version of 0.3.1 of the Coffee Break extension which might resolve the issue. Let me know if it helped once you have it installed.
